services:
  # Traditional Multisig Nodes (ports 3000-3002)
  multisig-node0:
    image: frost-custody:latest
    build: .
    container_name: multisig-node-0
    entrypoint: ["multisig-signer"]
    volumes:
      - ./config-node0.toml:/etc/config.toml:ro
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - signer-net

  multisig-node1:
    image: frost-custody:latest
    container_name: multisig-node-1
    entrypoint: ["multisig-signer"]
    volumes:
      - ./config-node1.toml:/etc/config.toml:ro
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - signer-net

  multisig-node2:
    image: frost-custody:latest
    container_name: multisig-node-2
    entrypoint: ["multisig-signer"]
    volumes:
      - ./config-node2.toml:/etc/config.toml:ro
    ports:
      - "3002:3000"
    restart: unless-stopped
    networks:
      - signer-net

  # FROST Signer Nodes (ports 4000-4002, internal only)
  frost-node0:
    image: frost-custody:latest
    container_name: frost-signer-node-0
    entrypoint: ["frost-service"]
    volumes:
      - ./frost-config-node0.toml:/etc/config.toml:ro
    networks:
      - frost-internal
    # No external ports - only aggregator can reach
    # role = "node" in config

  frost-node1:
    image: frost-custody:latest
    container_name: frost-signer-node-1
    entrypoint: ["frost-service"]
    volumes:
      - ./frost-config-node1.toml:/etc/config.toml:ro
    networks:
      - frost-internal

  frost-node2:
    image: frost-custody:latest
    container_name: frost-signer-node-2
    entrypoint: ["frost-service"]
    volumes:
      - ./frost-config-node2.toml:/etc/config.toml:ro
    networks:
      - frost-internal

  # FROST Address Aggregator (port 9000, exposed to CEX, LOW RISK)
  address-aggregator:
    image: frost-custody:latest
    container_name: address-aggregator
    entrypoint: ["frost-service"]
    volumes:
      - ./address-config.toml:/etc/config.toml:ro
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - frost-internal
      - cex-network
    depends_on:
      - frost-node0
      - frost-node1
      - frost-node2
    # role = "address" in config

  # FROST Signing Aggregator (port 8000, HIGH RISK - RESTRICT ACCESS!)
  signing-aggregator:
    image: frost-custody:latest
    container_name: signing-aggregator
    entrypoint: ["frost-service"]
    volumes:
      - ./signing-config.toml:/etc/config.toml:ro
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - frost-internal
      - cex-network
    depends_on:
      - frost-node0
      - frost-node1
      - frost-node2
    # role = "signer" in config

networks:
  signer-net:
    driver: bridge
  frost-internal:
    driver: bridge
    internal: true # No external access - signers isolated!
  cex-network:
    driver: bridge
    # CEX backend connects here
# FROST Custody - Bitcoin threshold signing system
# Profiles for different deployment scenarios:
#   docker-compose up multisig-node0 multisig-node1 multisig-node2  # Traditional multisig only
#   docker-compose up frost-node0 frost-node1 frost-node2 frost-aggregator  # FROST only
#   docker-compose up  # All services
