# FROST DKG Latency Test: 16-of-24 Threshold
#
# Architecture:
#   - 24 internal signer nodes (no exposed ports)
#   - 1 address aggregator (exposed port 9100)
#   - Client connects only to aggregator
#
# Usage:
#   docker-compose -f docker-compose.test-24.yml up --build -d
#   cargo run --bin dkg_latency_test
#   docker-compose -f docker-compose.test-24.yml down -v

services:
  # 24 FROST Signer Nodes (internal only, no exposed ports)
  frost-node-00:
    image: frost-custody:latest
    build: .
    container_name: frost-test-node-00
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-00.toml:/etc/config.toml:ro
      - frost-test-data-00:/data
    networks:
      - frost-test-internal

  frost-node-01:
    image: frost-custody:latest
    container_name: frost-test-node-01
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-01.toml:/etc/config.toml:ro
      - frost-test-data-01:/data
    networks:
      - frost-test-internal

  frost-node-02:
    image: frost-custody:latest
    container_name: frost-test-node-02
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-02.toml:/etc/config.toml:ro
      - frost-test-data-02:/data
    networks:
      - frost-test-internal

  frost-node-03:
    image: frost-custody:latest
    container_name: frost-test-node-03
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-03.toml:/etc/config.toml:ro
      - frost-test-data-03:/data
    networks:
      - frost-test-internal

  frost-node-04:
    image: frost-custody:latest
    container_name: frost-test-node-04
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-04.toml:/etc/config.toml:ro
      - frost-test-data-04:/data
    networks:
      - frost-test-internal

  frost-node-05:
    image: frost-custody:latest
    container_name: frost-test-node-05
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-05.toml:/etc/config.toml:ro
      - frost-test-data-05:/data
    networks:
      - frost-test-internal

  frost-node-06:
    image: frost-custody:latest
    container_name: frost-test-node-06
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-06.toml:/etc/config.toml:ro
      - frost-test-data-06:/data
    networks:
      - frost-test-internal

  frost-node-07:
    image: frost-custody:latest
    container_name: frost-test-node-07
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-07.toml:/etc/config.toml:ro
      - frost-test-data-07:/data
    networks:
      - frost-test-internal

  frost-node-08:
    image: frost-custody:latest
    container_name: frost-test-node-08
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-08.toml:/etc/config.toml:ro
      - frost-test-data-08:/data
    networks:
      - frost-test-internal

  frost-node-09:
    image: frost-custody:latest
    container_name: frost-test-node-09
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-09.toml:/etc/config.toml:ro
      - frost-test-data-09:/data
    networks:
      - frost-test-internal

  frost-node-10:
    image: frost-custody:latest
    container_name: frost-test-node-10
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-10.toml:/etc/config.toml:ro
      - frost-test-data-10:/data
    networks:
      - frost-test-internal

  frost-node-11:
    image: frost-custody:latest
    container_name: frost-test-node-11
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-11.toml:/etc/config.toml:ro
      - frost-test-data-11:/data
    networks:
      - frost-test-internal

  frost-node-12:
    image: frost-custody:latest
    container_name: frost-test-node-12
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-12.toml:/etc/config.toml:ro
      - frost-test-data-12:/data
    networks:
      - frost-test-internal

  frost-node-13:
    image: frost-custody:latest
    container_name: frost-test-node-13
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-13.toml:/etc/config.toml:ro
      - frost-test-data-13:/data
    networks:
      - frost-test-internal

  frost-node-14:
    image: frost-custody:latest
    container_name: frost-test-node-14
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-14.toml:/etc/config.toml:ro
      - frost-test-data-14:/data
    networks:
      - frost-test-internal

  frost-node-15:
    image: frost-custody:latest
    container_name: frost-test-node-15
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-15.toml:/etc/config.toml:ro
      - frost-test-data-15:/data
    networks:
      - frost-test-internal

  frost-node-16:
    image: frost-custody:latest
    container_name: frost-test-node-16
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-16.toml:/etc/config.toml:ro
      - frost-test-data-16:/data
    networks:
      - frost-test-internal

  frost-node-17:
    image: frost-custody:latest
    container_name: frost-test-node-17
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-17.toml:/etc/config.toml:ro
      - frost-test-data-17:/data
    networks:
      - frost-test-internal

  frost-node-18:
    image: frost-custody:latest
    container_name: frost-test-node-18
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-18.toml:/etc/config.toml:ro
      - frost-test-data-18:/data
    networks:
      - frost-test-internal

  frost-node-19:
    image: frost-custody:latest
    container_name: frost-test-node-19
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-19.toml:/etc/config.toml:ro
      - frost-test-data-19:/data
    networks:
      - frost-test-internal

  frost-node-20:
    image: frost-custody:latest
    container_name: frost-test-node-20
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-20.toml:/etc/config.toml:ro
      - frost-test-data-20:/data
    networks:
      - frost-test-internal

  frost-node-21:
    image: frost-custody:latest
    container_name: frost-test-node-21
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-21.toml:/etc/config.toml:ro
      - frost-test-data-21:/data
    networks:
      - frost-test-internal

  frost-node-22:
    image: frost-custody:latest
    container_name: frost-test-node-22
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-22.toml:/etc/config.toml:ro
      - frost-test-data-22:/data
    networks:
      - frost-test-internal

  frost-node-23:
    image: frost-custody:latest
    container_name: frost-test-node-23
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=error
    volumes:
      - ./tests/configs/node-23.toml:/etc/config.toml:ro
      - frost-test-data-23:/data
    networks:
      - frost-test-internal

  # Address Aggregator - Single public endpoint
  address-aggregator:
    image: frost-custody:latest
    container_name: frost-test-aggregator
    entrypoint: ["frost-service"]
    environment:
      - RUST_LOG=info
    volumes:
      - ./tests/configs/aggregator.toml:/etc/config.toml:ro
    ports:
      - "9100:9100" # Only this port is exposed
    networks:
      - frost-test-internal
      - frost-test-public
    depends_on:
      - frost-node-00
      - frost-node-01
      - frost-node-02
      - frost-node-03
      - frost-node-04
      - frost-node-05
      - frost-node-06
      - frost-node-07
      - frost-node-08
      - frost-node-09
      - frost-node-10
      - frost-node-11
      - frost-node-12
      - frost-node-13
      - frost-node-14
      - frost-node-15
      - frost-node-16
      - frost-node-17
      - frost-node-18
      - frost-node-19
      - frost-node-20
      - frost-node-21
      - frost-node-22
      - frost-node-23

networks:
  frost-test-internal:
    driver: bridge
    internal: true # Signer nodes isolated from external access
  frost-test-public:
    driver: bridge # Only aggregator accessible

volumes:
  frost-test-data-00:
  frost-test-data-01:
  frost-test-data-02:
  frost-test-data-03:
  frost-test-data-04:
  frost-test-data-05:
  frost-test-data-06:
  frost-test-data-07:
  frost-test-data-08:
  frost-test-data-09:
  frost-test-data-10:
  frost-test-data-11:
  frost-test-data-12:
  frost-test-data-13:
  frost-test-data-14:
  frost-test-data-15:
  frost-test-data-16:
  frost-test-data-17:
  frost-test-data-18:
  frost-test-data-19:
  frost-test-data-20:
  frost-test-data-21:
  frost-test-data-22:
  frost-test-data-23:
